PROFILE_QUESTIONS = [
    {
        "key": "name",
        "question": "What's your name?",
        "input_type": "text",
        "placeholder": "Enter your name",
    },
    {
        "key": "current_domain",
        "question": "What's your current professional domain?",
        "input_type": "select",
        "options": [
            "Technology/IT",
            "Healthcare",
            "Finance/Banking",
            "Education",
            "Marketing/Communications",
            "Design/Creative",
            "Business/Management",
            "Manufacturing/Engineering",
            "Student",
            "Other",
        ],
        "placeholder": "select your current domain",
    },
    {
        "key": "current_postion",
        "question": "What's your current specific role or position?",
        "input_type": "text",
        "placeholder": "The name of your current position",
    },
    {
        "key": "target_role",
        "question": "What specific job or role are you hoping to prepare for?",
        "input_type": "text",
        "placeholder": "Yorr target job title, tool or computer language",
    },
    {
        "key": "tech_experience_level",
        "question": "How would you describe your experience level with technology?",
        "input_type": "select",
        "options": [
            "Complete beginner - I rarely use computers beyond basic tasks",
            "Novice - I use computers regularly but don't know how they work",
            "Intermediate - I've done some coding or technical work",
            "Advanced - I work in tech but want to expand my skills",
            "Expert - I'm proficient but looking to specialize or pivot",
        ],
        "placeholder": "Select your experience level",
    },
    {
        "key": "learning_obstacles",
        "question": "What's your biggest challenge when it comes to learning new skills?",
        "input_type": "select",
        "options": [
            "Finding time in my schedule",
            "Staying motivated and consistent",
            "Understanding complex concepts",
            "Applying theory to practical projects",
            "Information overload/knowing where to start",
            "Access to good learning resources",
            "Lack of guidance or mentorship",
            "Other",
        ],
        "placeholder": "Select your biggest challenge",
    },
    {
        "key": "time_limit",
        "question": "What's your target timeframe for achieving your learning goals?",
        "input_type": "select",
        "options": [
            "Less than 3 months",
            "3-6 months",
            "6-12 months",
            "1-2 years",
            "More than 2 years",
            "No specific deadline",
        ],
        "placeholder": "Select your timeframe",
    },
    {
        "key": "preferred_learning_style",
        "question": "How do you learn best?",
        "input_type": "multi_select",
        "options": [
            "Video tutorials",
            "Reading books/documentation",
            "Interactive coding exercises",
            "Project-based learning",
            "Structured courses with deadlines",
            "Learning with others/group work",
            "One-on-one mentoring",
            "Trial and error/self-discovery",
        ],
        "placeholder": "Select preferred learning styles",
    },
    {
        "key": "learning_resources",
        "question": "Do you have access to any paid learning resources?",
        "input_type": "multi_select",
        "options": [
            "Paid online course platforms (Udemy, Coursera, etc.)",
            "Coding bootcamps",
            "College/university courses",
            "Technical books",
            "Professional mentorship",
            "None - prefer free resources only",
        ],
        "placeholder": "Select available resources",
    },
    {
        "key": "additional_info",
        "question": "Is there anything else you'd like to share about your learning preferences or goals?",
        "input_type": "text",
        "placeholder": "Any additional information",
    },
]
